### ISSUE TITLE
`_getVerificationMethod` frame may need tweaking

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/http-signature-zcap-verify#1]
See: https://github.com/digitalbazaar/edv-client/issues/16

**Comment by OR13** [comment]
`controller: {'@embed': '@never'}`

Fix is missing `@`

**Comment by OR13** [comment]
https://github.com/digitalbazaar/http-signature-zcap-verify/pull/3

**Comment by dlongley** [comment]
Thanks. Yeah, clearly we're missing tests. Fixed here: 1e06477db4b2b1b7dbc13e0a77deffb5d6c67b37
