### ISSUE TITLE
Reevaluate bitcore-message exceptions after upgrading to jsigs@5.

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/http-signature-zcap-verify#11]
karma configs make exceptions for bitcore-message which are part of EcdsaKoblitsz... which is being removed in jsigs@5.

it was copied for sure and no bitcore is not used here directly, but:

```
ls node_modules/bitcore-message
bower.json       dist  gulpfile.js  lib           README.md
CONTRIBUTING.md  docs  index.js     package.json  test
// it is there
```

and a grep for it in `node_modules` does show tons of results so some of the signature libraries still require it.
Removing it results in non-fatal karma errors:

```
ERROR in ./node_modules/bitcore-lib/lib/crypto/random.js
Module not found: Error: Can't resolve 'crypto' in '/work/ajones/digital_bazaar/http-signature-zcap-verify/node_modules/bitcore-lib/lib/crypto'
 @ ./node_modules/bitcore-lib/lib/crypto/random.js 15:15-32
 @ ./node_modules/bitcore-lib/index.js
 @ ./node_modules/bitcore-message/index.js
 @ ./node_modules/jsonld-signatures/lib/suites/EcdsaKoblitzSignature2016.js
 @ ./node_modules/jsonld-signatures/lib/suites.js
 @ ./node_modules/jsonld-signatures/lib/jsonld-signatures.js
 @ ./tests/10-verify.spec.js
```

so thanks for the check as it does appear it is still required.

_Originally posted by @aljones15 in https://github.com/digitalbazaar/http-signature-zcap-verify/pull/9_

**Comment by dlongley** [comment]
bitcore-message has been removed, closing.
