### ISSUE TITLE
TODO/FIXME Count 2

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/http-signature-zcap-verify#17]
- [ ] TODO: replace these with faster base64 implementation
       Commit: (a99cc97) Add core files.
       File:  [util-browser.js:7](https://github.com/digitalbazaar/http-signature-zcap-verify/blob/master/util-browser.js#L7)
       Dave Longley commented a year ago

  - [x] TODO: add parameters to check any other caveats in the capability as
       Commit: (a99cc97) Add core files.
       File:  [main.js:124](https://github.com/digitalbazaar/http-signature-zcap-verify/blob/master/main.js#L124)
       Dave Longley commented a year ago

**Comment by JSAssassin** [comment]
Closing. Opened new issue for the remaining TODO item.
