### ISSUE TITLE
Allow a JS Date instance to be passed to APIs

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/http-signature-zcap-verify#24]
Right now we only accept an integer (unix timestamp representing seconds since epoch). We should *additionally* accept a JS Date instance to make things simple for API callers.

**Comment by dmitrizagidulin** [comment]
See also https://github.com/digitalbazaar/http-signature-header/issues/49

**Comment by JSAssassin** [comment]
@dlongley can you please provide additional detail regarding this issue like where I should be making these changes?

**Comment by dlongley** [comment]
@JSAssassin, any public API method that currently accepts a date as an integer representing a unix timestamp should also be able to accept a Date instance.

**Comment by dmitrizagidulin** [comment]
Implemented in PR #25, closing.
