### ISSUE TITLE
TODO: replace with faster base64 implementation

### ISSUE THREAD

**Issue by JSAssassin** [digitalbazaar/http-signature-zcap-verify#27]
- [ ] TODO: replace these with faster base64 implementation
      Commit: (a99cc97) Add core files.
      Fi[util-browser.js:7](https://github.com/digitalbazaar/http-signature-zcap-verify/blob/master/util-browser.js#L7)
      Dave Longley commented 2 years ago

**Comment by dlongley** [comment]
Closing as unnecessary.
