### ISSUE TITLE
Add unit tests and CI

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/http-signature-zcap-verify#4]

**Comment by OR13** [comment]
We use Travis for public repos currently, but github actions is new and might be more fun to setup.

The universal resolver plans to use it: https://github.com/decentralized-identity/universal-resolver/actions/new

**Comment by aljones15** [comment]
@OR13 I will look into it. Time... very sparse. Will try.

Wow they have automated puppeteer tests: https://github.com/marketplace/actions/puppeteer-container

Weirdly no automated karma or mocha tests only Jest. This might be a fun thing to do some weekend as the scripts heavily resemble travis-ci scripts.

**Comment by aljones15** [comment]
Proposed Tests:

Proposed Tests for `verifyCapabilityInvocation`
  - Ed25519SignatureSuite || RSASignatureSuite
      - Positive
        - should verify a valid request
        - should add headers if `content-type` is in headers.
        - should verify with additionalHeaders
      - Negative:
        - should THROW if no `getInvokedCapability`
        - should  THROW if no `documentLoader`
        -  should THROW if verificationMethod type is not supported
        - should NOT verify if there is no url
        - should NOT verify if there are no headers
        - should NOT verify if host is not in expectedHost
        - should NOT verify if `keyId` can not be rereferenced by the `documentLoader`
        - should NOT verify if `keyId` has no `controller` property
        - should NOT verify if headers is missing `(key-id)`
        - should NOT verify if headers is missing `(created)`
        - should NOT verify if headers is missing `(expires)`
        - should NOT verify if headers is missing `(request-target)`
        - should NOT verify if headers is missing `host`
        - should NOT verify if headers is missing `capability-invocation`
        - should NOT verify (this might be a throw) if missing an expectedTarget

**Comment by dlongley** [comment]
`AssertionPurpose` and `AuthenticationPurpose` are not relevant here. The relevant purpose here is `CapabilityInvocation`. But even that purpose isn't exposed at the API level.

> should THROW if verificationMethod is in LDKeyPair

What does this mean?

I think the rest of the tests look ok.

**Comment by aljones15** [comment]
oh my I did not catch the Purpose so my apologies that was is kind of dumb I guess. Anyways, I'll stick with 2 suites.

that is a type on the test name should be:

`should THROW if verificationMethod is not supported by LDKeyPair`

I just changed this too:

`should THROW if verificationMethod keyType is not supported by LDKeyPair`

if the verificationMethod is not Ed25519 or RSA LDKeyPair throws:

https://github.com/digitalbazaar/crypto-ld/blob/892c5950b739847ae2aa2b893152a26f14f32a1d/lib/LDKeyPair.js#L114-L116

although if that functionality should be tested in this suite is another question entirely.

**Comment by dlongley** [comment]
Let's say "should THROW if verificationMethod type is not supported". The "LDKeyPair" stuff is an implementation detail. It's really about the verificationMethod type not matching the suite.

**Comment by aljones15** [comment]
> should THROW if verificationMethod type is not supported

Agreed and updated. Ok that's a test suite being worked on.

**Comment by OR13** [comment]
Github actions are the new travis, highly recommend.

**Comment by mattcollier** [comment]
@aljones15 please close this issue or advise on what is still outstanding.

**Comment by aljones15** [comment]
Closing this as tests are in master now. please create a new issue if test coverage needs to be expanded (I think more positive tests might be good in the future).
